using Curso_C_;
using CursoCSaharp;
using CursoCSharp;
//TipoPrimitivo.ImprimirTipos();
//EntradaSaidaDados.LerArmazenar();
//Exercicios.EntradaSaida();
//OperadoresAritmeticos.Soma();
//OperadoresAritmeticos.Subtracao();
//OperadoresAritmeticos.Divisao();
//OperadoresAritmeticos.Multiplicacao();
//OperadoresAritmeticos.Resto();
//OperadoresAritmeticos.Incremento();
//OperadoresAritmeticos.Decremento();
